os: linux
dist: xenial
language: python

services:
  - postgresql

jobs:
  include:
    - addons:
        postgresql: "9.5"
      env: DB="9.5"
      python: "3.5"
    - addons:
        postgresql: "9.6"
      env: DB="9.6"
      python: "3.5"
    - addons:
        postgresql: "10"
      env: DB="10"
      python: "3.5"
    - addons:
        postgresql: "9.5"
      env: DB="9.5"
      python: "3.6"
    - addons:
        postgresql: "9.6"
      env: DB="9.6"
      python: "3.6"
    - addons:
        postgresql: "10"
      env: DB="10"
      python: "3.6"
    - addons:
        postgresql: "9.5"
      env: DB="9.5"
      python: "pypy3.5"
    - addons:
        postgresql: "9.6"
      env: DB="9.6"
      python: "pypy3.5"
    - addons:
        postgresql: "10"
      env: DB="10"
      python: "pypy3.5"

before_install:
  - sudo systemctl stop postgresql
  - cd /etc/postgresql/$DB/main
  - sudo chmod ugo+rw pg_hba.conf
  - sudo cp pg_hba.conf old_pg_hba.conf
  - sudo echo "host pg8000_md5 all 127.0.0.1/32 md5" > pg_hba.conf
  - sudo echo "host pg8000_gss all 127.0.0.1/32 gss" >> pg_hba.conf
  - sudo echo "host pg8000_password all 127.0.0.1/32 password" >> pg_hba.conf
  - if [ ${DB} == "10" ]; then
      sudo echo "host pg8000_scram_sha_256 all 127.0.0.1/32 scram-sha-256" >> pg_hba.conf;
      sudo chmod ugo+rw postgresql.conf;
      sudo echo "password_encryption = scram-sha-256" >> postgresql.conf;
    fi
  - cat old_pg_hba.conf >> pg_hba.conf
  - sudo systemctl start postgresql@${DB}-main
  - psql -U postgres -tc 'create extension hstore;'
  - psql -U postgres -tc 'show server_version;'
  - psql -U postgres -tc "alter system set client_min_messages = notice;"
  - psql -U postgres -tc "alter user postgres with password 'pw';"
  - sudo systemctl reload postgresql@${DB}-main
  - psql -U postgres -tc 'show client_min_messages;'
  - cd $TRAVIS_BUILD_DIR

install:
  - pip install tox-travis

script:
  - tox
